### ISSUE TITLE
Tributary Release Checklist

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#229]
**Internal Code Audit**

- [x] LIP-3 
  - Implemented in #222 
  - [Spec](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-3.md)
- [x] LIP-8 
  - Implemented in #225 
  - [Spec](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-8.md)
- [x] LIP-9 
  - Implemented in #223 
  - [Spec](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-9.md)
- [x] LIP-11 
  - Implemented in #227 
  - [Spec](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-11.md)
- [x] Overall [code diff](https://github.com/livepeer/protocol/compare/9563609d98e7b517ab25b41087960c0a68d0d6aa...master) based on currently deployed contracts on mainnet

**Mainnet Deployment**

- [x] Deploy new contracts
  - LIP-3
    - Deploy the new LivepeerVerifier contract. Let the new contract address be `livepeerVerifierAddr`.
  - LIP-8 and LIP-11
    - Deploy the new BondingManager contract. Let the new contract address be `bondingManagerAddr`.
  - LIP-9
    - Deploy the new ServiceRegistry target contract. Let the new contract address be `serviceRegistryTargetAddr`.
    - Deploy the new ServiceRegistry proxy contract. Let the new contract address be `serviceRegistryProxyAddr`.
- [x] Pause Controller
  1. Submit a transaction to the governance multisig that executes the function call `Controller.pause()`.
  2. Confirm the transaction from first step.
- [x] Register new contracts
  - LIP-3
    1. Submit a transction to the governance multisig that executes the function call 
    `Controller.setContract(contractId("Verifier"), livepeerVerifierAddr)`.
    2. Confirm the transacton from first step.
  - LIP-8 and LIP-11
    1. Submit a transaction to the governance multisig that executes the function call 
    `Controller.setContract(contractId("BondingManagerTarget"), bondingManagerAddr)`.
    2. Confirm the transaction from first step.
  - LIP-9
    1. Submit a transaction to the governance multisig that executes the function call 
    `Controller.setContract(contractId("ServiceRegistryTarget"), serviceRegistryTargetAddr)`.
    2. Confirm the transaction from step 1.
    3. Submit a transaction to the governance multisig that executes the function call `Controller.setContract(contractId("ServiceRegistry"), serviceRegistryProxyAddr)`.
    4. Confirm the transaction from step 3.
- [x] Unpause Controller
  1. Submit a transaction to the governance multisig that executes the function call `Controller.unpause()`.
  2. Confirm the transaction from first step.

**Misc**

- [x] Update protocol specification
- [x] Document breaking changes for third party client developers and for node operators
- [x] Update deployed contract addresses in the wiki
