### ISSUE TITLE
PM Client MVP

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#283]
- [ ] As a broadcaster, I should be able to send PM tickets representing a transcoding price I find acceptable
- [ ] As a broadcaster, I should be able to send PM tickets with video segments without negatively impacting the latency of the transcoded stream
- [ ] As a broadcaster, I should have enough information to know when I need to top off my deposit and/or reserve and a suggested amount of funds 
- [ ] As a broadcaster, I should be able to manually create/withdraw a deposit and reserve and then all other Ethereum related actions will be automatically handled
- [ ] As a broadcaster, I should be able to see how much I paid orchestrators for transcoded video in terms of non-winning and winning tickets for various streams
- [ ] As an orchestrator, I should be able to accept PM tickets knowing that I will be able to profit from the value of winning tickets
- [ ] As an orchestrator, I should be able to generate PM ticket parameters that guarantee profitable winning ticket redemption regardless of the current Ethereum gas price
- [ ] As an orchestrator, I should be able to accept PM tickets without negatively impacting the latency of the transcoded stream
- [ ] As an orchestrator, I should be able to see how much I got paid for transcoding video in terms of non-winning and winning tickets for various streams
