### ISSUE TITLE
🌊Payment Accounting MVP (No Pixel Counting)

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#293]
Original proposal: https://github.com/livepeer/go-livepeer/issues/866

- [ ] An orchestrator should be able to advertise a price for N output pixels of transcoding work (not measuring input pixels and accounting for decoding costs at the moment)
- [ ] An orchestrator should be able to define a minimum credit requirement for a broadcaster such that the orchestrator will not transcode a segment unless the broadcaster meets the minimum credit requirement
- [ ] An orchestrator should be able to keep track of a broadcaster's current credit balance and whether it meets the current minimum credit requirement
- [ ] An orchestrator should be able to adjust its price to always guarantee profitable payment redemption based on the current transaction cost for payment redemption
- [ ] An orchestrator should be able to determine the number of output pixels in a transcoded result
- [ ] A broadcaster should be able to send payments that ensure that the broadcaster meets the minimum credit requirement for an orchestrator
